//
//  MBFieldTypes.h
//  Core
//
//  Created by Wido on 28-5-10.
//  Copyright 2010 Itude Mobile BV. All rights reserved.
//

// container types
#define C_SECTION @"SECTION"
#define C_ROW @"ROW"
#define C_MATRIXHEADER @"MATRIX-HEADER"
#define C_MATRIXROW @"MATRIX-ROW"
// cell types for use in identifiers
#define C_REGULARCELL @"REGULARCELL"
#define C_SUBTITLECELL @"SUBTITLECELL"
#define C_DROPDOWNLISTCELL @"DROPDOWNLISTCELL"
#define C_WEBVIEWCELL @"WEBVIEWCELL"
// field types
#define C_FIELD_LABEL @"LABEL"
#define C_FIELD_SUBLABEL @"SUBLABEL"
#define C_FIELD_BUTTON @"BUTTON"
#define C_FIELD_TEXT @"TEXT"
#define C_FIELD_IMAGE @"IMAGE"
#define C_FIELD_ICON @"ICON"
#define C_FIELD_INPUT @"INPUTFIELD"
#define C_FIELD_USERNAME @"USERNAMEFIELD"
#define C_FIELD_PASSWORD @"PASSWORDFIELD"
#define C_FIELD_DROPDOWNLIST @"DROPDOWNLIST"
#define C_FIELD_CHECKBOX @"CHECKBOX"
#define	C_FIELD_RADIOGROUPFIELD @"RADIOGROUP"
#define C_FIELD_DATETIMESELECTOR @"DATETIMESELECTOR"
#define C_FIELD_DATESELECTOR @"DATESELECTOR"
#define C_FIELD_TIMESELECTOR @"TIMESELECTOR"
#define C_FIELD_MATRIXTITLE @"MATRIX-TITLE"
#define C_FIELD_MATRIXCELL @"MATRIX-CELL"

// default field types
#define C_FIELD_STYLE_NAVIGATION @"NAVIGATION"
#define C_FIELD_STYLE_NETWORK @"NETWORK"
#define C_FIELD_STYLE_POPUP @"POPUP"

